# .air.toml 示例
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = ["README.md"]
  delay = 1000

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
